#!/usr/bin/perl

$nc = $ARGV[0];

sub files_in_dir {
    local $dir = shift;
    local @entries;

    opendir (DIR, $dir) || die;
    @entries = sort {$b <=> $a} (readdir DIR);
    closedir DIR;
    return reverse @entries;
}

$dir = "/mirror/var/spool/news/articles/gmane/comp/java/openjdk/announce";

foreach $file (files_in_dir($dir)) {
    if ($file =~ /^[0-9]+$/) {
	if ($nc) {
	    open(WEAVERD, "| nc localhost 8010") || die;
	    print WEAVERD "input $dir/$file\n";
	    close(WEAVERD);
	} else {
	    print "$dir/$file\n";
	}
    }
}


