#!/usr/bin/perl

$cutoff = $ARGV[0];

open (TAIL, "tail -n 300000 -f /tmp/history|") || die;

$found = 0;

while (<TAIL>) {
    chop;
    ($time, $file) = split;
    if ($cutoff) {
	if ($time gt $cutoff) {
	    $found = 1;
	}
    } else {
	if (! $found && ! $lasts{$file}) {
	    $found = 1;
	}
    }
    if ($found && ! $lasts{$file}) {
	next if $file =~ /gmane.config/;
	next unless $file =~ /^.var.spool.news.articles.gmane\/.*$/;
	$file = "$file";
	print "$_\n";
	$odir = $file;
	$odir =~ s/[0-9]+$//;
	if (-e $file) {
	    if (open (FILE, $file)) {
		$spam = 0;
		while (<FILE>) {
		    chop;
		    $spam = 1 if /^Xref.*gmane.spam.detected/i;
		    last if /^$/;
		}
		close FILE;
		if (! $spam) {
		    print "Threadable.\n";
		    system("echo 'input /mirror$file' | nc plane 8010");
		    #sleep(1);
		}
	    }
	}
    }
}
