#!/usr/bin/perl

$cutoff = $ARGV[0];

#open (TAIL, "tail -n 800000 -f /tmp/history|") || die;
open(TAIL, "nc news 8002 |") || die;

$found = 0;
$found = 1 if (! $cutoff);

$host = "localhost";

while (<TAIL>) {
    chop;
    ($time, $file) = split;
    if ($cutoff && $time gt $cutoff && /^[0-9]{8}/) {
	$found = 1;
    }
    if ($found) {
	open(STAMP, ">/var/tmp/weaver-stamp") || die;
	print STAMP "$time\n";
	close STAMP;

	next if $file =~ /gmane.config/;
	next unless $file =~ /^.var.spool.news.articles.gmane\/.*$/;
	$file = "$file";
	print "$_\n";
	$odir = $file;
	$odir =~ s/[0-9]+$//;
	$file =  "/mirror$file";
	if (-e $file) {
	    if (open (FILE, $file)) {
		$spam = 0;
		while (<FILE>) {
		    chop;
		    $spam = 1 if /^Xref.*gmane.spam.detected/i;
		    last if /^$/;
		}
		close FILE;
		if (! $spam) {
		    print "Threadable.\n";
		    system("echo 'input $file' | nc $host 8010");
		    if (! ($times++ % 100)) {
			system("echo 'flush' | nc $host 8010");
		    }
		}
	    }
	}
    }
}
